"""Initial migration

Revision ID: 1d1e287a4b8a
Revises: 
Create Date: 2024-06-30 20:38:30.434632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1e287a4b8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_email', table_name='patients')
    op.drop_index('ix_patients_id', table_name='patients')
    op.drop_index('ix_patients_name', table_name='patients')
    op.drop_table('patients')
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_super_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='patients_pkey')
    )
    op.create_index('ix_patients_name', 'patients', ['name'], unique=False)
    op.create_index('ix_patients_id', 'patients', ['id'], unique=False)
    op.create_index('ix_patients_email', 'patients', ['email'], unique=True)
    # ### end Alembic commands ###
