"""Исправление недочетов с именами

Revision ID: a4b92f087b05
Revises: 1d1e287a4b8a
Create Date: 2024-06-30 21:42:55.872546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b92f087b05'
down_revision: Union[str, None] = '1d1e287a4b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
