"""changes schedule doctor

Revision ID: ab049ecdea24
Revises: d7b47d7c9001
Create Date: 2024-07-01 11:57:22.613942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab049ecdea24'
down_revision: Union[str, None] = 'd7b47d7c9001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_time_slots', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_doctor_time_slots_date'), 'doctor_time_slots', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_time_slots_date'), table_name='doctor_time_slots')
    op.drop_column('doctor_time_slots', 'date')
    # ### end Alembic commands ###
